export const vehicleCategories = [
  {
    id: "economy",
    name: "Economy",
    badge: "Budget",
    price: "₹12/km",
    description: "Affordable rides for everyday travel.",
    features: [
      "Budget Friendly",
      "Chilled AC",
      "4 Passengers",
      "2-3 Luggage Bags",
    ],
    vehicles: ["Swift Dzire", "Toyota Etios", "Honda Amaze"],
  },
  {
    id: "standard",
    name: "Standard",
    badge: "Most Popular",
    price: "₹15/km",
    description: "Extra comfort for family and business trips.",
    features: [
      "Spacious MPV/SUV",
      "Dual AC Blowers",
      "6-7 Passengers",
      "4-5 Luggage Bags",
    ],
    vehicles: ["Maruti Ertiga", "Kia Carens", "Toyota Innova"],
  },
  {
    id: "business",
    name: "Business & Luxury",
    badge: "Luxury",
    price: "₹20/km",
    description: "Luxury travel with premium executive comfort.",
    features: [
      "Luxury Captain Chairs",
      "Professional Chauffeur",
      "Premium Interior",
      "Priority Service",
    ],
    vehicles: [
      "Toyota Innova Crysta",
      "Force Urbania",
      "Tempo Traveller",
    ],
  },
];

export const rideExtras = [
  {
    id: "water",
    name: "Mineral Water Bottle",
    price: 30,
    complimentary: false,
  },
  {
    id: "newspaper",
    name: "Daily Newspaper",
    price: 20,
    complimentary: false,
  },
  {
    id: "snacks",
    name: "Light Snacks",
    price: 150,
    complimentary: false,
  },
  {
    id: "cold-drink",
    name: "Cold Drink",
    price: 80,
    complimentary: false,
  },
  {
    id: "baby-seat",
    name: "Baby Seat",
    price: 300,
    complimentary: false,
  },
  {
    id: "wheelchair",
    name: "Wheelchair Assistance",
    price: 500,
    complimentary: false,
  },
  {
    id: "meet-greet",
    name: "Airport Meet & Greet",
    price: 400,
    complimentary: false,
  },
  {
    id: "name-board",
    name: "Driver Name Board",
    price: 150,
    complimentary: false,
  },
  {
    id: "wifi",
    name: "Wi-Fi Hotspot",
    price: 100,
    complimentary: false,
  },
  {
    id: "charger",
    name: "Mobile Charger",
    price: 0,
    complimentary: true,
  },
  {
    id: "tissue",
    name: "Tissue Paper",
    price: 0,
    complimentary: true,
  },
  {
    id: "multiple-stops",
    name: "Multiple Stops",
    price: 300,
    complimentary: false,
  },
  {
    id: "pet",
    name: "Pet Friendly Ride",
    price: 250,
    complimentary: false,
  },
  {
    id: "senior",
    name: "Senior Citizen Assistance",
    price: 200,
    complimentary: false,
  },
];